#!/bin/bash

if [ -z "$1" ]
  then
    podman compose up --remove-orphans -d && podman compose logs -f --tail 20
  else
    podman compose up --remove-orphans -d $1 && podman compose logs -f --tail 20 $1
fi

