#!/bin/bash

source ./service_cli

if [[ "$1" == "mm2" ]]; then
  podman compose stop mm2
elif [[ -z ${1-} ]]; then
  for key in "${!service_cli[@]}"; do
    echo "stopping $key"
    ${service_cli[$key]} stop
  done
  echo "sleeping 30 seconds"
  sleep 30
  podman compose stop
else
  ${service_cli[$1]} stop
  echo "sleeping 30 seconds"
  sleep 30
  podman compose stop $1
fi
